name: Build Java Plugin

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Compile Java code
        run: |
          mkdir -p out
          javac -d out $(find src -name "*.java")

      - name: Package JAR
        run: |
          jar cf ActiveScanPlusPlus.jar -C out .

      - name: Upload plugin JAR
        uses: actions/upload-artifact@v4
        with:
          name: ActiveScanPlusPlus
          path: ActiveScanPlusPlus.jar
